OEWebApplicationApp/OEWebApplicationApp/Controllers/ApprovalController.cs
using Microsoft.AspNetCore.Mvc;
using OEWebApplicationApp.Models;
using System.Data;

namespace OEWebApplicationApp.Controllers
{
    public class ApprovalController : Controller
    {
        private IHttpContextAccessor Accessor;
        public string NewUserName()
        {
            string value;
            value = HttpContext.User.Identity.Name.Remove(0, 14).ToLower();
            //value = "CSaguez";

            return value;
        }
        //instace of helper classes======================================================
        private ManagerTblCgyoe tblCgyoeManager = new();
        private ClassFunctions function = new();
        private ClassConfig configclass = new();

        // GET: =========================================================================
        public ActionResult Index(string id)
        {
            ClassFunctions function = new();
            ClassConfig configclass = new();
            //ViewBag.UserName = configclass.username();
            ViewBag.UserName = NewUserName();
            ViewBag.DateTime = function.dateTime();
            try
            {
                var OElist = tblCgyoeManager.GetViewApproverOERequest(id, NewUserName());
                if (!OElist.Any() )
                {
                    OElist = tblCgyoeManager.GetViewApproverOERequest(id, NewUserName()).OrderByDescending(x => x.RequestId).ToList();
                    TempData["Info Message"] = "-- Message Center: You do not have any approvals --";
                    return View(OElist);
                }
                else
                {
                    OElist = tblCgyoeManager.GetViewApproverOERequest(id, NewUserName()).OrderByDescending(x => x.RequestId).ToList();
                    return View(OElist);
                }
            }
            catch (Exception ex)
            {
                TempData["Info Message"] = ex.Message;
                return View();
            }
           // var OElist = tblCgyoeManager.GetViewApproverOERequest(id);
            //return View(OElist);
        }

        // DETAILS: =========================================================================
        public ActionResult Details(int id)
        {
            ClassFunctions function = new();
            ClassConfig configclass = new();
            //ViewBag.UserName = configclass.username();
            ViewBag.UserName = NewUserName();
            ViewBag.DateTime = function.dateTime();
            try
            {
                var OElist = tblCgyoeManager.GetViewOEById(id, NewUserName());
                return View(OElist);
            }
            catch (Exception ex)
            {
                TempData["Info Message"] = ex.Message;
                return View();
            }
            //var OElist = tblCgyoeManager.GetViewOEById(id);
            //return View(OElist);
        }

        // EDIT: =========================================================================
        public ActionResult Edit(int id)
        {
            ClassFunctions function = new();
            ClassConfig configclass = new();
            //ViewBag.UserName = configclass.username();
            ViewBag.UserName = NewUserName();
            ViewBag.DateTime = function.dateTime();
            ViewBag.status = tblCgyoeManager.StatusList();
            try
            {
                var OElist = tblCgyoeManager.GetViewOEById(id, NewUserName()).FirstOrDefault();
                return View(OElist);
            }catch (Exception ex)
            {
                TempData["Info Message"] = ex.Message;
                return View();
            }

        }

        // POST: ApprovalController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Edit")]
        public ActionResult Edit(int id, TblCgyoeModel TblCgyoeModel)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool IsUpdated = tblCgyoeManager.ApproveRequest(id, TblCgyoeModel, NewUserName());
                    if (IsUpdated)
                    {
                        ViewData["SendToName"] = TblCgyoeModel.RequestedBy + "@morrisonhomes.ca";
                        string ? reason = TblCgyoeModel.Reason;
                        string ? request = TblCgyoeModel.Request;
                        double gst = Math.Round((double)TblCgyoeModel.Gstamount,2);
                        double totalAmount = Math.Round((double)TblCgyoeModel.TotalAmount,2);
                        string ? vendor = TblCgyoeModel.Vendor;
                        function.WriteToFile( id, vendor, reason, request, gst,  totalAmount);
                        TempData["Info Message"] = "--Message Center: Approval Notification Sent to " + ViewData["SendToName"] + " --";
                        //TODO change email to approver
                        string email1 = TblCgyoeModel.RequestedBy + "@morrisonhomes.ca";
                        string email = "evan.doucett@morrisonhomes.ca";
                        string body = "Dear Recipient, \n \n Please be advised that your OE "+ TblCgyoeModel.RequestId + " has been approved. ";
                        string subject = "-- OE Approval Notification.";
                        function.SendEmail(email1, body, subject);
                        return RedirectToAction("Index", new { id = "notApproved" });
                    }
                    else
                    {
                        TempData["Info Message"] = "--Message Center: Approval was NOT Success--";
                        return RedirectToAction("Index", new { id = "notApproved" });
                    }
                }
                return RedirectToAction("Index", new { id = "notApproved" });
            }
            catch (Exception ex)
            {

                TempData["Info Message"] = ex.Message;
                return RedirectToAction("Index", new { id = "notApproved" });
            }
        }

        // DELETE/REJECT: =========================================================================
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ApprovalController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                TempData["Info Message"] = "--Message Center: Delete was success--";
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                TempData["Info Message"] = "--Message Center: Delete was NOT success--";
                return View();
            }
        }

        public ActionResult Reject(int id, string requestedby)
        {
            ViewData["Id"] = id;
            ViewData["RequestedBy"] = requestedby;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Reject(int id, string RequestedBy, TblCgyoeModel tblCgyoeModel)
        {
            try
            {
                //TODO change email to requested
                string email1 = RequestedBy + "@morrisonhomes.ca";
                string email = "evan.doucett@morrisonhomes.ca";
                string body = "Dear Recipient, \n \n Please be advised that your OE request " + id + " has been REJECTED.\n Reason for rejection: " + tblCgyoeModel.RejectReason;
                string subject = "-- OE Rejection Notification.";
                TempData["Info Message"] = "--Message Center: Approval Rejection Sent to " + email1 + " --";
                function.SendEmail(email1, body, subject);
                RejectDelete(id, tblCgyoeModel);
                return RedirectToAction("Index", new { id = "notApproved" });
            }
            catch
            {
                TempData["Info Message"] = "--Message Center: Reject was NOT success--";
                return View();
            }
        }
        public ActionResult RejectDelete(int id, TblCgyoeModel tblCgyoe)
        {
            ManagerImage managerImage = new ManagerImage();
            try
            {
                //remove oe request from db
                string result = tblCgyoeManager.Delete(id, NewUserName());
                //remove oe scanned images from db and file
                managerImage.DeleteAllImages(id, tblCgyoe);
                return RedirectToAction("Index", new { id = "notApproved" });
            }
            catch (Exception ex)
            {
                TempData["Info Message"] = ex.Message;
                return View();
            }

        }//Delete

    }//CLASS
}//NAMESPACE

OEWebApplicationApp/OEWebApplicationApp/Controllers/ImageController.cs
using Microsoft.AspNetCore.Mvc;
using OEWebApplicationApp.Models;

namespace OEWebApplicationApp.Controllers
{
    public class ImageController : Controller
    {
        private IHttpContextAccessor Accessor;
        public string NewUserName()
        {
            string value;
            value = HttpContext.User.Identity.Name.Remove(0, 14).ToLower();
            //value = "CSaguez";

            return value;
        }
        private ClassFunctions function = new();
        private ClassConfig configclass = new();
        private ManagerImage ManagerImage = new();

        //IMAGE pull by request id================================================================================================
        public ActionResult Index(string id, string page)
        {

            ClassFunctions function = new();
            ClassConfig configclass = new();
            //ViewBag.UserName = configclass.username();
            ViewBag.UserName = NewUserName();
            ViewBag.DateTime = function.dateTime();
            try
            {
                var OElist = ManagerImage.GetImages(id);
                if (!OElist.Any())
                {
                    TempData["Info Message"] = "-- Message Center: There are no attachments uploaded for document " + id + " --";
                    OElist = ManagerImage.GetImages(id);
                    ViewData["Page"] = page;
                    ViewData["MyRequestId"] = id;
                    return View(OElist);
                }
                else
                {
                    OElist = ManagerImage.GetImages(id);
                    ViewData["Page"] = page;
                    ViewData["MyRequestId"] = id;
                    return View(OElist);
                }
            }
            catch (Exception ex)
            {
                TempData["Info Message"] = ex.Message;
                ViewData["Page"] = page;
                ViewData["MyRequestId"] = id;
                return View();
            }
        }//Index

        //create image by id=====================================================================================================
        public IActionResult Create(string id, string page)
        {
            ViewData["Page"] = page;
            ViewData["MyRequestId"] = id;
            ImageModel model = new();
            return View(model);
        }//Create


        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ImageModel model, string page)
        {
            ViewData["MyRequestId"] = page;
            model.IsResponse = true;
            //File Path============================================================================
            string path = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot\\Files");

            //create directory if not exist========================================================
            if (!Directory.Exists(path))
                Directory.CreateDirectory(path);

            FileInfo fileInfo = new FileInfo(model.File.FileName);

            if (!fileInfo.Exists)
            {
            //create a file name: requestid location (CGY EDM) DDMMYYYYHHMM=========================
                string dateTime = DateTime.Now.ToString("ddMMyyyyhhmmss");
                string extentsion = fileInfo.Extension;
                string fileName = model.RequestId + model.Location + dateTime  + fileInfo.Extension;
                string fileNameWithPath = Path.Combine(path, fileName);
                ViewData["Page"] = page;
                ViewData["MyPath"] = fileNameWithPath;
            //Copy file to the local system and check for pdf=======================================
                if(extentsion.ToLower() == ".pdf")
                    {
                        using (var stream = new FileStream(fileNameWithPath, FileMode.Create))
                        {
                            model.File.CopyTo(stream);
                            TempData["Info Message"] = "-- Message Center: File upload successfull --";
                        }
                        model.IsSuccess = true;
                        //update the database with location=================================================
                        ManagerImage.UpdateImageTbl(fileName, fileNameWithPath, model);
                        return RedirectToAction("Index", new { id = model.RequestId, page = ViewData["MyRequestId"] });
                    }
                    else
                    {
                        TempData["Info Message"] = "-- Message Center: Upload Failed - PDF only --";
                        return RedirectToAction("Index", new { id = model.RequestId, page = ViewData["MyRequestId"] });
                    }
            }
            else
            {
                TempData["Info Message"] = "-- Message Center: File upload NOT successfull --";
                return View("Index", new { id = model.RequestId, page = ViewData["MyRequestId"] });
            }
        }//Create

        //DELETE====================================================================================
        public IActionResult Delete(string id, string page)
        {
            var OElist = ManagerImage.GetImage(id).FirstOrDefault();
            ViewData["Page"] = page;
            return View(OElist);
        }//Delete

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(string id, ImageModel imageModel, string page)
        {
            ViewData["Page"] = page;
            try
            {
                string result = ManagerImage.DeleteImage(id, imageModel);
                if (result == "Success")
                {
                    TempData["Info Message"] = "-- Message Center: Image delete was Success --";
                    return RedirectToAction("Index", "Request", new { id = imageModel.RequestId, page = ViewData["MyRequestId"] });
                }
                else
                {
                    TempData["Info Message"] = "-- Message Center: Image Delete was NOT success --";
                    return RedirectToAction("Index","Request", new { id = imageModel.RequestId, page = ViewData["MyRequestId"] });
                }
            }
            catch (Exception ex)
            {
                TempData["Info Message"] = ex.Message;
                return View();
            }


        }//Delete

    }//class
}//namespace

OEWebApplicationApp/OEWebApplicationApp/Views/Approval/Details.cshtml
@model IEnumerable<OEWebApplicationApp.Models.TblCgyoeModel>

@{
    ViewData["Title"] = "Details";
}
<div class="container-fluid boxShadow">
    <div class="row">
        <div class="col-4 "><h3>Approved Details</h3></div>
        <a asp-area="" asp-controller="Approval" asp-action="Index"><h4>Back to Approve List</h4></a>
        <div class="col-4"></div>
        <div class="col-4"> </div>
    </div>
</div>
<div class="container-fluid">
    <div class="row">
        <div class="col-2"></div>
        <div class="col-8 ">
            <table class="table table-striped table-bordered boxShadow">
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.RequestId)</td>
                            <td>@Html.DisplayFor(modelItem => item.RequestId)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.Vendor)</td>
                            <td>@Html.DisplayFor(modelItem => item.Vendor)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.VendorName)</td>
                            <td>@Html.DisplayFor(modelItem => item.VendorName)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.RequestedBy)</td>
                            <td> @Html.DisplayFor(modelItem => item.RequestedBy)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.Glaccount)</td>
                            <td> @Html.DisplayFor(modelItem => item.Glaccount)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.AutoApproveThreshold)</td>
                            <td> @Html.DisplayFor(modelItem => item.AutoApproveThreshold)</td>
                        </tr>
                        <tr>
                            <td> @Html.DisplayNameFor(model => model.Amount)</td>
                            <td>@Html.DisplayFor(modelItem => item.Amount)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.Gstamount)</td>
                            <td>@Html.DisplayFor(modelItem => item.Gstamount)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.TotalAmount)</td>
                            <td>@Html.DisplayFor(modelItem => item.TotalAmount)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.Gstincluded)</td>
                            <td>@Html.DisplayFor(modelItem => item.Gstincluded)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.Budgeted)</td>
                            <td>@Html.DisplayFor(modelItem => item.Budgeted)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.AutoApproved)</td>
                            <td>@Html.DisplayFor(modelItem => item.AutoApproved)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.Request)</td>
                            <td> @Html.DisplayFor(modelItem => item.Request)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.PurchaseDate)</td>
                            <td> @Html.DisplayFor(modelItem => item.PurchaseDate) </td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.ApprovedBy)</td>
                            <td>@Html.DisplayFor(modelItem => item.ApprovedBy)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.ApprovedDate)</td>
                            <td>@Html.DisplayFor(modelItem => item.ApprovedDate)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.Status)</td>
                            <td>@Html.DisplayFor(modelItem => item.Status)</td>
                        </tr>
                        <tr>
                            <td> @Html.DisplayNameFor(model => model.Reason)</td>
                            <td>@Html.DisplayFor(modelItem => item.Reason)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.Attachment)</td>
                            <td>@Html.DisplayFor(modelItem => item.Attachment)</td>
                        </tr>
                        <tr>
                            <td>@Html.DisplayNameFor(model => model.Timestamp)</td>
                            <td>@Html.DisplayFor(modelItem => item.Timestamp)</td>
                        </tr>
                        <div class="container">
                            <div class="row">
                                <div class="col-sm-4"></div>
                                <div class="col-sm-4"></div>
                                <div class=" col-sm-4"></div>
                            </div>
                        </div>
                        <hr />
                    }
                </tbody>
            </table>
        </div>
        <div class="col-2"></div>
    </div>
</div>
<hr />

OEWebApplicationApp/OEWebApplicationApp/Views/Approval/Index.cshtml
@model IEnumerable<OEWebApplicationApp.Models.TblCgyoeModel>

@{
    ViewData["Title"] = "ApproveOEApprovals";
}

<div class="container-fluid boxShadow">
    <div class="row">
        <div class="col-4 "><h3>Operating Expense Approval</h3></div>
        <a asp-area="" asp-controller="Home" asp-action="Index"><h4>Back to Home Page</h4></a>
        <div class="col-4"></div>
        <div class="col-4 justify-content-end"></div>
    </div>
</div>
<hr />
@if (TempData["Info Message"] != null)
{
    <div class="container-flex d-flex justify-content-center boxShadow bg-info">
        <div class="row">
            <div class="" id="top">
                <h2 class="text-black"><strong>@TempData["Info Message"]</strong></h2>
            </div>
        </div>
    </div>
    <hr />
}
<div class="container-fluid boxShadow">
    <div class="row justify-content-start">
        <div class="col-1 text-center button text-black">Filters: </div>
        <div class="col-1 text-center button"><a asp-controller="Approval" asp-action="Index" asp-route-id="All" id="All">View All</a></div>
        <div class="col-1 text-center button"><a asp-controller="Approval" asp-action="Index" asp-route-id="Approved" id="Approved">Approved</a></div>
        <div class="col-1 text-center button"><a asp-controller="Approval" asp-action="Index" asp-route-id="notApproved">Not Approved</a></div>
    </div>
</div>
<table class="table table-striped table-bordered table-hover boxShadow">
    <thead>
        <tr>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.RequestId)
            </th>
            @*            <th>
            @Html.DisplayNameFor(model => model.Vendor)
            </th>*@
            <th class="text-center">
                @Html.DisplayNameFor(model => model.VendorName)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.RequestedBy)
            </th>
            @*            <th>
            @Html.DisplayNameFor(model => model.Glaccount)
            </th>*@
            @*            <th>
            @Html.DisplayNameFor(model => model.AutoApproveThreshold)
            </th>*@
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Amount)
            </th>
            @*            <th>
            @Html.DisplayNameFor(model => model.Gstvalue)
            </th>*@
            @*            <th>
            @Html.DisplayNameFor(model => model.Gstamount)
            </th>*@
            <th class="text-center">
                @Html.DisplayNameFor(model => model.TotalAmount)
            </th>
            @*            <th>
            @Html.DisplayNameFor(model => model.Gstincluded)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.Budgeted)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.AutoApproved)
            </th>*@
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Request)
            </th>
            <th class="text-center">
                @Html.DisplayNameFor(model => model.PurchaseDate)
            </th>
            @*            <th>
            @Html.DisplayNameFor(model => model.ApprovedBy)
            </th>*@
            @*            <th>
            @Html.DisplayNameFor(model => model.ApprovedDate)
            </th>*@
            <th class="text-center">
                @Html.DisplayNameFor(model => model.Status)
            </th>
            @*            <th>
            @Html.DisplayNameFor(model => model.Reason)
            </th>*@
            @*            <th>
            @Html.DisplayNameFor(model => model.Timestamp)
            </th>*@
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.RequestId)
                </td>
                @*                <td class="text-center">
            @Html.DisplayFor(modelItem => item.Vendor)
            </td>*@
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.VendorName)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.RequestedBy)
                </td>
                @*                <td class="text-center">
            @Html.DisplayFor(modelItem => item.Glaccount)
            </td>*@
                @*            <td>
            @Html.DisplayFor(modelItem => item.AutoApproveThreshold)
            </td>*@
                <td class="text-center">
                    @string.Format("{0:C}", item.Amount)
                </td>
                @*            <td>
            @Html.DisplayFor(modelItem => item.Gstvalue)
            </td>*@
                @*                <td class="text-center">
            @string.Format("{0:C}", item.Gstamount)
            </td>*@
                <td class="text-center">
                    @string.Format("{0:C}", item.TotalAmount)
                </td>
                @*            <td>
            @Html.DisplayFor(modelItem => item.Gstincluded)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.Budgeted)
            </td>
            <td>
            @Html.DisplayFor(modelItem => item.AutoApproved)
            </td>*@
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.Request)
                </td>
                <td class="text-center">
                    @Html.DisplayFor(modelItem => item.PurchaseDate)
                    @*            </td>
                <td class="text-center">
                @Html.DisplayFor(modelItem => item.ApprovedBy)
                </td>*@
                    @*                <td class="text-center">
                @Html.DisplayFor(modelItem => item.ApprovedDate)
                </td>*@
                <td class="text-center fw-bold">
                        @Html.DisplayFor(modelItem => item.Status)
                </td>
                    @*            <td>
            @Html.DisplayFor(modelItem => item.Reason)
            </td>*@
                    @*            <td>
            @Html.DisplayFor(modelItem => item.Timestamp)
            </td>*@
                <td>

                        @if (item.Status != "Approved")
                        {
                        <a asp-controller="Approval" asp-action="Edit" asp-route-id="@item.RequestId" class="text-danger fw-bold">Approve</a>
                        <a asp-controller="Approval" asp-action="Details" asp-route-id="@item.RequestId" class="text-black">Details</a>
                        <a asp-controller="Image" asp-action="Index" asp-route-id="@item.RequestId" asp-route-page="approval" class="text-black ">Attachments</a>
@*                        <a asp-controller="Request" asp-action="Print"
                           asp-route-page="approval"
                           asp-route-Requestid="@item.RequestId"
                           asp-route-vendor="@item.Vendor"
                           asp-route-purchaseDate="@item.PurchaseDate"
                           asp-route-glAccount="@item.Glaccount"
                           asp-route-request="@item.Request"
                           asp-route-amountAmt="@item.Amount"
                           asp-route-taxAmt="@item.Gstamount"
                           asp-route-totalAmt="@item.TotalAmount"
                           asp-route-vendorname="@item.VendorName"
                           class="text-black ">Print</a>*@
                        }
                        else
                        {
                        <a asp-controller="Approval" asp-action="Details" asp-route-id="@item.RequestId" class="text-black">Details</a>
                        <a asp-controller="Image" asp-action="Index" asp-route-id="@item.RequestId" asp-route-page="approval" class="text-black  ">Attachments</a>
                        <a asp-controller="Request" asp-action="Print"
                           asp-route-page="approval"
                           asp-route-Requestid="@item.RequestId"
                           asp-route-vendor="@item.Vendor"
                           asp-route-purchaseDate="@item.PurchaseDate"
                           asp-route-glAccount="@item.Glaccount"
                           asp-route-request="@item.Request"
                           asp-route-amountAmt="@item.Amount"
                           asp-route-taxAmt="@item.Gstamount"
                           asp-route-totalAmt="@item.TotalAmount"
                           asp-route-vendorName="@item.VendorName"
                           class="text-black ">Print</a>
                        }
                </td>
            </tr>
        }
    </tbody>
</table>
<a href="#top"><h3 class="text-black">TOP</h3></a>
