OEWebApplicationApp/OEWebApplicationApp/Controllers/RequestController.cs
using Microsoft.AspNetCore.Mvc;
using OEWebApplicationApp.Models;
using System.Data;

namespace OEWebApplicationApp.Controllers
{
    public class RequestController : Controller
    {
        private IHttpContextAccessor Accessor;
        public string NewUserName()
        {
            string value;
            value = HttpContext.User.Identity.Name.Remove(0, 14).ToLower();
            //value = "CSaguez";
            //value = "edoucett";
            return value;
        }

        //instace of helper classes======================================================
        private ClassFunctions function = new();
        private ClassConfig configclass = new();
        private ManagerTblCgyoe tblCgyoeManager = new();
        private ManagerApmMasterVendor apmMasterVendorManager = new();
        private ManagerViewGLaccount viewGLaccountManager = new();
        private ManagerImage managerImage = new();

        // GET: =========================================================================
        [Route("RequestedItemUser")]
        public ActionResult Index(string id)
        {
            ClassFunctions function = new();
            ClassConfig configclass = new();
            //ViewBag.UserName = configclass.username();
            ViewBag.UserName = NewUserName();
            ViewBag.DateTime = function.dateTime();

            try
            {
                var OElist = tblCgyoeManager.GetViewOERequest(id, NewUserName());
                if (!OElist.Any())
                {
                    TempData["Info Message"] = "-- Message Center: You do not have any request --";
                    OElist = tblCgyoeManager.GetViewOERequest(id, NewUserName()).OrderByDescending(x => x.RequestId).ToList();
                    return View(OElist);
                }
                else
                {
                    OElist = tblCgyoeManager.GetViewOERequest(id, NewUserName()).OrderByDescending(x => x.RequestId).ToList();
                    return View(OElist);
                }
            }catch (Exception ex)
            {
                TempData["Info Message"] = ex.Message;
                return View();
            }
        }//Index


        // Details: =====================================================================
        [Route("DetailsItem/{id}")]
        public ActionResult Details(int id)
        {
            ClassFunctions function = new();
            ClassConfig configclass = new();
            //ViewBag.UserName = configclass.username();
            ViewBag.UserName = NewUserName();
            ViewBag.DateTime = function.dateTime();
            try
            {
                var OElist = tblCgyoeManager.GetViewOERequestById(id, NewUserName());
                return View(OElist);
            }
            catch (Exception ex)
            {
                TempData["Info Message"] = ex.Message;
                return View();
            }
            //var OElist = tblCgyoeManager.GetViewOERequestById(id);
            //return View(OElist);
        }
        public ActionResult Print2(int id)
        {
            ClassFunctions function = new();
            ClassConfig configclass = new();
            //ViewBag.UserName = configclass.username();
            ViewBag.UserName = NewUserName();
            ViewBag.DateTime = function.dateTime();
            try
            {
                var OElist = tblCgyoeManager.GetViewOERequestById(id, NewUserName());
                return View(OElist);
            }
            catch (Exception ex)
            {
                TempData["Info Message"] = ex.Message;
                return View();
            }
            //var OElist = tblCgyoeManager.GetViewOERequestById(id);
            //return View(OElist);
        }

        // Create: =====================================================================
        //[Route("CreateItem")]
        public ActionResult Create()
        {
            string userName = NewUserName();
            //values from file==================================================
            //ViewBag.UserName = configclass.username();
            ViewBag.UserName = userName;
            ViewBag.DateTime = function.dateTime();
            ViewBag.GstValue = configclass.ConfigGST();
            //dropdown list==================================================
            ViewBag.Budgeted = tblCgyoeManager.BudgetList();
            ViewBag.autoApproved = tblCgyoeManager.AutoApproveList();
            ViewBag.status = tblCgyoeManager.StatusList();
            ViewBag.gstInc = tblCgyoeManager.GstList();
            //total var======================================================
            ViewBag.ttlamt = 0;
            ViewBag.amount = 0;
            ViewBag.newthreshold = 0;
            ViewBag.gstamt = 0;
            //select database lists==========================================
            TblCgyoeModel tblCgyoeModel = new TblCgyoeModel();
            string ? name = tblCgyoeModel.GetVendorName();
            string ? threashold = tblCgyoeModel.GetGlAccount();
            ViewBag.vendors = apmMasterVendorManager.GetViewVendor(NewUserName()).ToList();
            ViewBag.glAccounts = viewGLaccountManager.GetAllGlAccounts(userName);
            ViewBag.vendName = apmMasterVendorManager.GetViewVendor(NewUserName()).ToList().Where(x => x.Vendor == name);
            ViewBag.approverGK = viewGLaccountManager.GetAllGlAccounts(userName).ToList().Where(x => x.AccountCustomField == threashold);


            return View();
        }

        //Calculations: ===============================================================
        [HttpPost]
        [ValidateAntiForgeryToken]
        [ActionName("Create")]
        public IActionResult Createcalc(TblCgyoeModel tblCgyoeModel)
        {
            //values from file==================================================
            //ViewBag.UserName = configclass.username();
            ViewBag.UserName = NewUserName();
            ViewBag.DateTime = function.dateTime();
            ViewBag.GstValue = configclass.ConfigGST();
            //dropdown list=====================================================
            ViewBag.Budgeted = tblCgyoeManager.BudgetList();
            ViewBag.autoApproved = tblCgyoeManager.AutoApproveList();
            ViewBag.status = tblCgyoeManager.StatusList();
            ViewBag.gstInc = tblCgyoeManager.GstList();
            string userName = NewUserName();
            string ? name = tblCgyoeModel.GetVendorName();
            string ? threashold = tblCgyoeModel.GetGlAccount();

            if (ModelState.IsValid)
            {
                ViewBag.vendors = apmMasterVendorManager.GetViewVendor(NewUserName()).ToList();
                ViewBag.glAccounts = viewGLaccountManager.GetAllGlAccounts(userName);                       
                ViewBag.vendName = apmMasterVendorManager.GetViewVendor(NewUserName()).ToList().Where(x => x.Vendor == name);
                ViewBag.threashold = viewGLaccountManager.GetAllGlAccounts(userName).ToList().Where(x => x.AccountCustomField == threashold);
                ViewBag.approverGK = viewGLaccountManager.GetAllGlAccounts(userName).ToList().Where(x => x.AccountCustomField == threashold);
                ViewBag.gstamt = tblCgyoeModel.CalculateGST();
                ViewBag.ttlamt = tblCgyoeModel.CalculateTotalValue();
                ViewBag.newAmt = tblCgyoeModel.CalculateAmount();
                ViewBag.newthreshold = ((double)viewGLaccountManager.GetThreshold(tblCgyoeModel.Glaccount, userName) - (double)tblCgyoeModel.CalculateTotalValue());
            }
            else
            {
                ViewBag.ttlamt = 0;
                ViewBag.gstamt = 0;
                ViewBag.newAmt = 0;
                ViewBag.vendors = apmMasterVendorManager.GetViewVendor(NewUserName()).ToList();
                ViewBag.glAccounts = viewGLaccountManager.GetAllGlAccounts(userName);
                ViewBag.vendName = "";
                ViewBag.approverGK = "";
                ViewBag.newthreshold = 0;
            }

            return View(tblCgyoeModel);
        }

        //Create: ==================================================================
        [HttpPost]
        [ActionName("CreateNew")]
        [ValidateAntiForgeryToken]
        public ActionResult Createupdate(TblCgyoeModel tblCgyoe)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    bool IsUpdated = tblCgyoeManager.createProduct(tblCgyoe, NewUserName());
                    if (IsUpdated)
                    {
                        ViewData["SendToName"] = tblCgyoe.ApprovedBy + "@morrisonhomes.ca";
                        TempData["Info Message"] = "--Message Center: Creation Successfully send to " + ViewData["SendToName"] +" --";
                        //TODO: change email to approver
                        string email1 = tblCgyoe.ApprovedBy + "@morrisonhomes.ca";
                        string email = "evan.doucett@morrisonhomes.ca";
                        string body = "Dear Recipient, \n \n Please be advised that you have an OE approval. ";
                        string subject = "-- OE Request Notification.";
                        function.SendEmail(email1, body, subject);
                        string lastEntry = tblCgyoeManager.GetLastEntryByUser(NewUserName());
                        return RedirectToAction("Create", "Image", new { id = lastEntry, page = "request" });
                        //return RedirectToAction("Index", new { id = "notApproved" });
                    }
                    else
                    {
                        TempData["Info Message"] = "--Message Center: Creation NOT Successful--";

OEWebApplicationApp/OEWebApplicationApp/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace OEWebApplicationApp.Controllers
{
    public class SettingsController : Controller
    {
        public string NewUserName()
        {
            string value;
            value = HttpContext.User.Identity.Name.Remove(0, 14).ToLower();
            //value = "CSaguez";

            return value;
        }
        public IActionResult Index()
        {
            /*calls username, GST, CONFIG FILE LOCATION, USER ADDRESS*/
            ClassFunctions function = new();
            ClassConfig configclass = new();
            ViewBag.Address = configclass.Address();
            ViewBag.UserName = NewUserName();
            ViewBag.GST = configclass.ConfigGST();
            ViewBag.CONFLOC = configclass.ConfigLocation();
            ViewBag.EXPLOC = configclass.ExportLocation();
            ViewBag.MorSQL = configclass.MorSQLConnections();
            ViewBag.DateTime = function.dateTime();
            ViewBag.Vmortl = configclass.vMortlSQLConnections();
            ViewBag.SMTP = configclass.EmailSMTP();
            ViewBag.PORT = configclass.EmailPort();
            ViewBag.FROM = configclass.EmailFrom();
            ViewBag.test = configclass.MorSQLConnections();

            return View();
        }
    }
}

OEWebApplicationApp/OEWebApplicationApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OEWebApplicationApp</title>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jspdf/1.5.3/jspdf.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.3/html2pdf.bundle.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/0.4.1/html2canvas.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.22/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>

    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <script src="~/js/site.js" asp-append-version="true"></script>
    <link rel="stylesheet" href="~/OEWebApplicationApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container-fluid p-2">
                <img class="d-inline-block align-text-top bg-white m-1 p-2" src="~/Images/MH_Logo_BLACK.png" width="180" height="58"></img>
@*                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">Morrison Homes </a>*@
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-black h5 m-3" id="top" asp-area="" asp-controller="Home" asp-action="Index">Home Page</a>
                        </li>
@*                        <li class="nav-item">
                            <a class="nav-link text-light h5" asp-area="" asp-controller="Request" asp-action="Index">Requests</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light h5" asp-area="" asp-controller="Approval" asp-action="Index">Approvals</a>
                        </li>*@
@*                        <li class="nav-item">
                            <a class="nav-link text-light h5" asp-area="" asp-controller="Request" asp-action="apm">Document Mgr</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light h5" asp-area="" asp-controller="Request" asp-action="gls">Customer Letters</a>
                        </li>*@
@*                        <li class="nav-item">
                            <a class="nav-link text-light h5" asp-area="" asp-controller="Home" asp-action="UnderConstruction">Scheduling</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark h5" asp-area="" asp-controller="Home" asp-action="UnderConstruction">Schedule Lookup</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark h5" asp-area="" asp-controller="Home" asp-action="UnderConstruction">Trade List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark h5" asp-area="" asp-controller="Home" asp-action="UnderConstruction">Vendor Reporting</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark h5" asp-area="" asp-controller="Home" asp-action="UnderConstruction">Zero $ PO</a>
                        </li>*@

                    </ul>
                    <a class="nav-link text-light " hidden asp-area="" asp-controller="Settings" asp-action="Index">Settings</a>
                    <div><label><span class="text-light"> User: @ViewBag.UserName</span> </label></div>
@*                    <div><label><span class="text-light"> User: @ViewBag.ServerName</span> </label></div>*@

                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        <main role="main" class="pb-1">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer fw-bold">
        Morrison Homes: Calgary
@*        <div class="container">
            <div class="row">
                <div class="col-sm-4" id="bottom">Morrison Homes: Calgary</div>
            </div>
        </div>*@
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

OEWebApplicationApp/OEWebApplicationApp/Views/Shared/_Layout1.cshtml
<!DOCTYPE html>

<html lang="en">
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <title>@ViewBag.Title</title>
</head>
<body class="bg-white m-5 p-5">
    <div>
        @RenderBody()
    </div>
</body>
</html>